<?php
/*******************************************/
/* MySQL Datenbankbackup                   */
/* Modul "lang_en.inc"                    */
/* Version 1.0 , GNU TAW24 Germany         */
/* Author Transatlantic-Web                */
/* http://www.taw24.de                     */
/*******************************************/

//  -------------------------------------------------------------------------------------

// HTML - Ausgabe

$title     = "Database Backup (MySQL - DUMP V1.0)";
$system    = "Server System: "; 
$phpversion= "  / PHP - Version: ";
$dbname    = "Databasename";
$tcount    = "Table Counter";
$size      = "Filesize";
$status    = "Status";
$err       = "No table available";
$info      = "Database - Backup OK.<BR>SQL-File directory: /"; 
$allsize   = "Completed Filesize :";
$copyright = "<p> <b>PHP Script written by <a href=http://www.taw24.de>Transatlantic-Web</a>, 2002</b> <p>";

// Dump - File 

$dump1     = "# Backup created by Transatlantic-Web at ";
$dump2     = "# Database: ";
$dump3     = "# Tablename: "; 




?>