<?php
/*******************************************/
/* MySQL Datenbankbackup                   */
/* Modul "lang_de.inc"                    */
/* Version 1.0 , GNU TAW24 Germany         */
/* Author Transatlantic-Web                */
/* http://www.taw24.de                     */
/*******************************************/

//  -------------------------------------------------------------------------------------

// HTML - Ausgabe

$title     = "Datenbank Backup (MySQL - DUMP V1.0)";
$system    = "Betriebssystem: "; 
$phpversion= "  / PHP - Version: ";
$dbname    = "DB Name";
$tcount    = "Anzahl Tabellen";
$size      = "Groesse";
$status    = "Status";
$err       = "Keine Tabelle übergeben";
$info      = "Das Server - Backup wurde erfolgreich durchgeführt.<BR>Die Dateien befinden sich Im Verzeichniss /"; 
$allsize   = "Gesamt Platzverbrauch :";
$copyright = "<p> <b>PHP Script written by <a href=http://www.taw24.de>Transatlantic-Web</a>, 2002</b> <p>";

// Dump - File 

$dump1     = "# Backup created by Transatlantic-Web am ";
$dump2     = "# Datenbank: ";
$dump3     = "# Tabellenname: "; 




?>